### ISSUE TITLE
scope doesn't work.                        go to the game. click x 

### ISSUE THREAD

**Issue by stefanimno** [VenomiXeD/3NDIssues#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stefanimno** [comment]
how do you use github

**Comment by VenomiXeD** [comment]
Resolved(?) in **Version 2022-10-01a**
