### ISSUE TITLE
open-top LLUVs with M40 recoilless rifle-type recoilless rifles

### ISSUE THREAD

**Issue by shiba2016** [VenomiXeD/3NDIssues#20]
![image_2022-08-24_205019800](https://user-images.githubusercontent.com/111321917/186549266-9a28b767-8747-46a8-ab63-791099107295.png)
this for non 4NSB troopas so normal ground has anti-tank capabilities without having to rely on the stupid TOW launchers hidden around the map like NVA troops in a fucking jungle

**Comment by VenomiXeD** [comment]
Issue #21
