### ISSUE TITLE
hit registration

### ISSUE THREAD

**Issue by smallchinchilla** [VenomiXeD/3NDIssues#22]
https://medal.tv/games/roblox/clips/Afq0exe5FTtB4/d1337V16dtbT?invite=cr-MSxEWlUsMjcwODk2MDks
https://medal.tv/games/roblox/clips/AfuZu_UPgt2qk/d13374yeyO4v?invite=cr-MSxxd20sMjcwODk2MDks
https://medal.tv/games/roblox/clips/AfuNa_r2Y2dGg/d1337qG83pYx?invite=cr-MSxOdXcsMjcwODk2MDks

**Comment by VenomiXeD** [comment]
Resolved(?) in **Version 2022-10-01a**
