### ISSUE TITLE
reload indicator

### ISSUE THREAD

**Issue by stefanimno** [VenomiXeD/3NDIssues#3]
having to manually press R with only a small indicator that you aren't loaded is most likely going to be frustrating for 3nd and raiders alike

having some sort of text along the lines of [You don't have a shell loaded! Press R!] like a couple seconds after you've fired would be nice

**Comment by farty84** [comment]
something like this with white-to-grey flashing text whenever the shell isn't loaded would be good for new people and raiders
![r](https://user-images.githubusercontent.com/111185245/184496065-b69da361-7afe-4b8d-8714-0b77855de473.jpg)

**Comment by VenomiXeD** [comment]
Completed as of **Version 2022-08-14a**.
